-- AlterTable
ALTER TABLE "StoolData" RENAME COLUMN "date" TO "start_date";
ALTER TABLE "StoolData"
ADD COLUMN     "created_on" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "end_date" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "StoolFutureData" RENAME COLUMN "date" TO "start_date";
ALTER TABLE "StoolFutureData"
ADD COLUMN     "end_date" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "UrineData" RENAME COLUMN "date" TO "start_date";
ALTER TABLE "UrineData"
ADD COLUMN     "created_on" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "end_date" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "UrineFutureData" RENAME COLUMN "date" TO "start_date";
ALTER TABLE "UrineFutureData"
ADD COLUMN     "end_date" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
